### ISSUE TITLE
Please remove dell.com from whitelists

### ISSUE THREAD

**Issue by jmptbl** [rspamd/maps#14]
Hello. For the past few weeks Dell have been sending me a lot of spam, and their domain is whitelisted in spf_dkim_whitelist.inc and surbl-whitelist.inc.  Their unsubscribe systems don't work.  Please can their whitelist entries be removed from rspamd?  Screenshots attached.

![Screen Shot 2019-12-02 at 16 18 38](https://user-images.githubusercontent.com/1299110/69971013-8d7a6680-151f-11ea-9a86-f7213b58c65c.png)
![Screen Shot 2019-12-02 at 16 17 26](https://user-images.githubusercontent.com/1299110/69971015-8e12fd00-151f-11ea-85a9-8acf6f9ea598.png)
![Screen Shot 2019-12-02 at 16 17 00](https://user-images.githubusercontent.com/1299110/69971017-8e12fd00-151f-11ea-8317-74858f344405.png)

**Comment by moisseev** [comment]
The message looks legitimate. If you have problems with the unsubscribe system, would you contact their support?

**Comment by jmptbl** [comment]
The message is unsolicited commercial email, aka UCE, aka SPAM. I have never subscribed to them, and should not have to unsubscribe nor undertake the inconvenience and expense of contacting a large corporatation's helpdesk that will most likely not understand or engage with such a problem.

It makes no sense that an anti-spam project is suggesting this logic and whitelisting this domain. How does this serve the project's objectives?

**Comment by vstakhov** [comment]
Hello, we have studied your suggestion and decided not to undertake any action. Thank you for your report, have a good day!
